version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "9111:9111"

  post-service:
    build:
      context: ./post-service
    ports:
      - "9112:9112"
    depends_on:
      - kafka

  notification-service:
    build:
      context: ./notification-service
    ports:
      - "9113:9113"
    depends_on:
      - redis
      - kafka

  redis:
    image: "redis:alpine"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
