global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:9111']

  - job_name: 'post-service'
    static_configs:
      - targets: ['post-service:9112']

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:9113']
